name: Apply Branch Protection Rules

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  protect-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Apply branch protection rules
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{
            "required_status_checks": null,
            "enforce_admins": false,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": false,
              "required_approving_review_count": 1
            },
            "restrictions": null
          }'
          echo "ran"
